"""add image url to blogs

Revision ID: d75d6fa5f6e5
Revises: b9405083d607
Create Date: 2026-05-19 10:28:12.963611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75d6fa5f6e5'
down_revision: Union[str, Sequence[str], None] = 'b9405083d607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'image_url')
    # ### end Alembic commands ###
